# Generated by Django 3.1.4 on 2020-12-11 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('compelete', models.BooleanField(default=False)),
                ('created', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
