# Generated by Django 3.1.4 on 2020-12-11 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('var7_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='note',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
